api:
  'base_url': "https://transparencia.campinas.sp.gov.br/index.php?"
  'actions': 'action=ws&mode=getDespesas&ano={year}&mesinicio={begin}&mestermino={month}&tipotr={despesa}'

cleaning:
  'date_column': 'mesAno'

  'str_columns_to_parse':
    - 'UnidadeGestoraDESC'
    - 'CredorDESC'
    - 'NaturezaDESC'

  'numeric_columns_to_parse':
    - 'ValorTransacao'
    - 'ValorEmpenhado'

despesa_types:
  - 'empenho'
  - 'liquidacao'
  - 'pagamento'

value_column:
  'empenho': 'ValorEmpenhado'
  'liquidacao': 'ValorTransacao'
  'pagamento': 'ValorTransacao'

operations:
  'sum': 'valor total'
  'max': 'maior valor no período'
  'mean': 'valor médio dos gastos no período'